# Generated by Django 4.2.7 on 2023-12-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('athleteId', models.IntegerField(primary_key=True, serialize=False)),
                ('refreshTokenCode', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ShortLivedAccessToken',
            fields=[
                ('athleteId', models.IntegerField(primary_key=True, serialize=False)),
                ('shortLivedAccessTokenCode', models.CharField(max_length=1000)),
                ('expiresAt', models.DateTimeField()),
            ],
        ),
    ]
