# Generated by Django 4.2.7 on 2024-01-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('backendstrava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.IntegerField()),
                ('state', models.CharField(choices=[('active', 'active'), ('close', 'close')], max_length=10)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('active', 'active'), ('close', 'close')], max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='athleteId',
            new_name='athlete_id',
        ),
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='refreshTokenCode',
            new_name='refresh_token_code',
        ),
        migrations.RenameField(
            model_name='shortlivedaccesstoken',
            old_name='athleteId',
            new_name='athlete_id',
        ),
        migrations.RenameField(
            model_name='shortlivedaccesstoken',
            old_name='expiresAt',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='shortlivedaccesstoken',
            old_name='shortLivedAccessTokenCode',
            new_name='short_lived_access_token_code',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('strava_id_activity', models.IntegerField(primary_key=True, serialize=False)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendstrava.serie')),
            ],
        ),
    ]
